# Generated by Django 5.1.3 on 2025-06-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dateofbirth',
        ),
    ]
